version: "3"

services:
  dev:
    image: nampdn/tensorflow-pytorch:latest
    environment:
      - ACCEPT_INTEL_PYTHON_EULA=yes
    ports:
      - 8888:8888
    volumes:
      - ./src:/tf/notebooks
      - ./jupyter:/root/.jupyter
